# Site
repository: mbaharan.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Reza Baharani
title: Ph.D. in Computer Engeering
email: mbaharan@uncc.edu
website: mbaharan.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  mbaharan
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: mbaharani
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
orcid_username: 0000-0002-7844-3181

# Additional icon links
additional_links:
- title: mbaharan.github.io
  icon: fas fa-globe
  url: https://mbaharan.github.io
- title: Google Scholar
  icon: fas fa-graduation-cap
  url: https://scholar.google.com/citations?user=LjWpX1AAAAAJ&hl=en
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Reza Baharani, and I have a Ph.D. degree in computer engineering. My thesis was about hardware acceleration and implementation of deep separable convolutional neural networks for micro-controller and FPGA platforms with a focus on both spatial (visual) and temporal (time series) domains.

  <mark>Python</mark>, <mark>C</mark>, and <mark>C++</mark> are my most proficient software programming languages, and <mark>SystemVerilog</mark> and <mark>VHDL</mark> are my best hardware modeling languages. <mark>PyTorch</mark> is also my main framework for modeling DNNs.

content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: UNC, Charlotte
        caption: 2017 - 2021
        sub_title: Ph.D. 
        #quote: >
        #  Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          When I was a student at UNC Charlotte, I learned almost all the key skills in the field of machine learning and specifically deep learning in both the spatial (visual) and temporal dimensions. Furthermore, I have developed my skills as a team member and learned how to manage a group of talented individuals to implement and accomplish our desired goals.

      - layout: left
        title: The University of Tehran
        caption: 2009 - 2012
        sub_title: Master
        #quote: >
        #  Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          I have pursued my dream of becoming a hardware engineer at the University of Tehran. It was during my education that I learned the fundamental skills and knowledge of computer architecture, hardware modeling, and hardware verification. Design space exploration of a hardware implementation of neuro-fuzzy models was my first project relating to the hardware acceleration of machine learning algorithms.

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title:  Agile Temporal Convolutional Network (ATCN)
        link: https://arxiv.org/pdf/2011.05260.pdf
        # link_text: Project Website
        additional_links:
          - title:  github.com/TeCSAR-UNCC/ATCN
            icon: fab fa-github
            url: https://github.com/TeCSAR-UNCC/ATCN
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Resource-Efficient Processing of Time Series on Edge
        description: | # this will include new lines to allow paragraphs
          One dimension of deep learning, which has recently emerged in Cyber-Physical Systems (CPS), is time series analysis and forecasting. Recurrent networks, especially two elaborated models, namely, LSTM and GRU, are synonymous with time series analysis due to its notable success in sequence modeling problems. However, these models suffer from two significant issues: 1) gradient instability and 2) fewer levels of parallelization. I am currently working on a novel extension of TCN  for light-weight real-time sequence processing on embedded and edge devices for CPS applications. I have methodologically applied the acquired techniques in computer vision to TCN to decrease computational complexity and the model size of TCN to make it applicable for edge devices.

      - layout: top-middle
        title:  DeepDive
        link: https://arxiv.org/pdf/2007.09490.pdf
        # link_text: Project Website
        #additional_links:
        #  - title:  github.com/TeCSAR-UNCC/ATCN
        #    icon: fab fa-github
        #    url: https://github.com/TeCSAR-UNCC/ATCN
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          An Integrative Algorithm/Architecture Co-Design for Deep Separable Convolutional Neural Networks
        description: | # this will include new lines to allow paragraphs
          I led a team of three master students to develop a fully vertical framework, named DeepDive, for agile implementation of state-of-the-art deep separable convolutions such as MobileNetV2 and EfficientNet families for the Xilinx Ultrascale Zynq MPSoC FPGA platforms.

      - layout: top-middle
        title:  Tufan
        #link: https://arxiv.org/pdf/2007.09490.pdf
        # link_text: Project Website
        #additional_links:
        #  - title:  github.com/TeCSAR-UNCC/ATCN
        #    icon: fab fa-github
        #    url: https://github.com/TeCSAR-UNCC/ATCN
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Low-Power Throughput Architecture for Acceleration of EfficientNet on Cloud FPGAs
        description: | # this will include new lines to allow paragraphs
          Tunan is an extension of DeepDive-Backend designed to support low-power throughput-oriented EfficientNet inference on cloud FPGA platforms such as Alveo U50.

      - layout: top-middle
        title:  DeepTrack
        link: https://arxiv.org/pdf/2108.00505.pdf
        # link_text: Project Website
        #additional_links:
        #  - title:  github.com/TeCSAR-UNCC/ATCN
        #    icon: fab fa-github
        #    url: https://github.com/TeCSAR-UNCC/ATCN
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Lightweight Deep Learning for Vehicle Trajectory Prediction in Highways
        description: | # this will include new lines to allow paragraphs
          For real-time vehicle trajectory prediction in highways, I developed DeepTrack as an agile algorithm with smaller model size and lower computational requirements. Contrary to previous methods, which used LSTMs, the vehicle dynamics were encoded with Agile Temporal Convolutional Networks (ATCNs) to provide more accurate time prediction with fewer computations.

      - layout: top-middle
        title:  Deep RACE
        link: https://arxiv.org/pdf/1908.01244.pdf
        # link_text: Project Website
        additional_links:
          - title:  github.com/TeCSAR-UNCC/Deep_RACE
            icon: fab fa-github
            url: https://github.com/TeCSAR-UNCC/Deep_RACE
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Real-time deep learning at the edge for scalable reliability modeling of Si-MOSFET power electronics converters
        description: | # this will include new lines to allow paragraphs
          Deep Learning Reliability Awareness of Converters at the Edge (Deep RACE) is a novel approach that allows for real-time reliability modeling and prediction of MOSFETs power electronics converters. Deep RACE offers a holistic solution that comprises algorithm advances and full system integration (from the cloud down to the edge node) to create a near real-time reliability awareness. On the algorithm side, we proposed a deep learning algorithmic solution based on stacked LSTM for collective reliability training and inference across multiple MOSFET converters.

      - layout: top-middle
        title:  REVAMP<sup>2</sup>T
        link: https://arxiv.org/pdf/1911.09217.pdf
        # link_text: Project Website
        additional_links:
          - title:  github.com/TeCSAR-UNCC/Edge-Video-Analytic
            icon: fab fa-github
            url: https://github.com/TeCSAR-UNCC/Edge-Video-Analytic
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Real-Time Edge Video Analytics for Multicamera Privacy-Aware Pedestrian Tracking
        description: | # this will include new lines to allow paragraphs
         As communities utilize technologies such as smart traffic cameras, the resulting data enables detection of suspicious activity and anomaly behavior, as well as crowd behavior analysis. My involvement in this project included Multi-Target Multi-Camera Tracking (MTMCT). Two subtasks can be identified in MTMCT: 1) target reidentification (reID) and 2) target trajectory. The MTMCT is a drastically difficult task due to having multiple cameras with no overlapping scenes and an unknown number of people seen in the cameras. Our team worked on an ensemble of deep neural networks, such as ResNet-50, MobileNet-V2, tinyYOLO, and OpenPose, to reID a target and process its trajectory.

      - layout: top-middle
        title:  CDFG of X86 Instructions
        #link: https://arxiv.org/pdf/1911.09217.pdf
        # link_text: Project Website
        #additional_links:
        #  - title:  github.com/TeCSAR-UNCC/Edge-Video-Analytic
        #    icon: fab fa-github
        #    url: https://github.com/TeCSAR-UNCC/Edge-Video-Analytic
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Dependency graph extraction from X86 and ARM assembly codes
        description: | # this will include new lines to allow paragraphs
         I worked on implementing a front-end for a VLIW-like processor which would issue instructions based on their dependencies beyond the scope of basic blocks. Hence, I created a Python code to analyze the dependency graph of X86 and ARM instructions and identify independent instructions across various basic blocks to increase overall Instruction Per Cycle (IPC).

      - layout: top-middle
        title:  FPGA Engineer Intern
        #link: https://arxiv.org/pdf/1911.09217.pdf
        # link_text: Project Website
        #additional_links:
        #  - title:  github.com/TeCSAR-UNCC/Edge-Video-Analytic
        #    icon: fab fa-github
        #    url: https://github.com/TeCSAR-UNCC/Edge-Video-Analytic
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Astranis Space Technologies Corp.
        
        description: | # this will include new lines to allow paragraphs
         I designed and verified a generic True Dual-Port Memory for Microsemi RTG4 FPGA in SystemVerilog.

      - layout: top-middle
        title:  FPGA Engineer Intern
        #link: https://arxiv.org/pdf/1911.09217.pdf
        # link_text: Project Website
        #additional_links:
        #  - title:  github.com/TeCSAR-UNCC/Edge-Video-Analytic
        #    icon: fab fa-github
        #    url: https://github.com/TeCSAR-UNCC/Edge-Video-Analytic
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Astranis Space Technologies Corp.
        description: | # this will include new lines to allow paragraphs
         I developed a generic Bus Functional Modeling (BFM) of AXI Stream (AXIS) based on Object-Oriented Programming (OOP) and callback functions to model different flavors of AXIS in SystemVerilog.

  - title: Teaching and Academic Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: UNC, Charlotte
        #link: boringcompany.com
        # link_text: boringcompany.com
        # sub_title: Senior Network System Administrator
        caption: Aug 2017 - Aug 2021
        #quote: >
        description: | # this will include new lines to allow paragraphs
          - Developed a simulator for G-Share, one-level, two-level global, two-level local branch predictors in python.
          - Developed a parameterized cache simulator in python.
          - TA for Advanced Embedded System Design
          - TA for Network Theory I

      - layout: left
        title: Ferdowsi University of Mashhad
        #link: boringcompany.com
        # link_text: boringcompany.com
        # sub_title: Senior Network System Administrator
        caption: Jan 2013 - March 2017
        #quote: >
        description: | # this will include new lines to allow paragraphs
          - Lecturer in digital system design for FPGA platforms
          - Thermal management of SMT and non-SMT high-performance homogenous multi-core processors
          - Cross-compiling Linux and developing customized drivers for NIOS II soft-core processor

      - layout: left
        title: Higher Education of Bahar
        #link: boringcompany.com
        # link_text: boringcompany.com
        # sub_title: Senior Network System Administrator
        caption: Sept 2014 - March 2015
        #quote: >
        description: | # this will include new lines to allow paragraphs
          - Lecturer in Computer Architecture
          - Lecturer in Digital Logic Circuit Desing


  #- title: A Little More About Me
  #  layout: text
  #  content: | # this will include new lines to allow paragraphs
  #    Alongside my interests in networks and software engineering some of my other interests and hobbies are:
  #    - Rock climbing
  #    - Gaming
  #    - Knitting
  #    - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      #Look at this cool image  

#![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
